// This file contains game data such as Starter Packages, lists of arcanum and other data.

export const starterPackages = [
  // 1 HP
  [
    {
      equipment: ['Sword (d6)', 'Pistol (d6)', 'Modern Armour'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby unearthly beings',
    },
    {
      equipment: ['Sword (d6)', 'Pistol (d6)', 'Modern Armour'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby unearthly beings',
    },
    {
      equipment: ['Sword (d6)', 'Pistol (d6)', 'Modern Armour'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby unearthly beings',
    },
    {
      equipment: ['Sword (d6)', 'Pistol (d6)', 'Modern Armour'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby unearthly beings',
    },
    {
      equipment: ['Sword (d6)', 'Pistol (d6)', 'Modern Armour'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby unearthly beings',
    },
    {
      equipment: ['Sword (d6)', 'Pistol (d6)', 'Modern Armour'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby unearthly beings',
    },
    {
      equipment: ['Sword (d6)', 'Pistol (d6)', 'Modern Armour'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby unearthly beings',
    },
    {
      equipment: ['Rifle (d8 B)', 'Bayonet (d6)'],
      arcanum: true,
      companion: 'Lighter Boy',
      specialInformation: '',
    },
    {
      equipment: ['Rifle (d8 B)', 'Modern Armour'],
      arcanum: true,
      companion: 'Hound',
      specialInformation: '',
    },
    {
      equipment: ['Club (d6)', 'Throwing Knives'],
      arcanum: true,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Pistol (d6)', 'Ether', 'Poison'],
      arcanum: true,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Cane (d6)', 'Acid', 'Spyglass'],
      arcanum: true,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Brace of Pistols (d8 B)', 'Canary', 'Ether'],
      arcanum: false,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Musket (d8 B)', 'Pocket-watch', 'Bomb'],
      arcanum: false,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Halberd (d8 B)', 'Fake Pistol', 'Artificial Lung'],
      arcanum: false,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Garotte (d6)', 'Musket (d8 B)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Mute',
    },
  ],
  // 2 HP
  [
    {
      equipment: ['Musket (d8 B)', 'Sword (d6)', 'Flashbang'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby Arcana'
    },
    {
      equipment: ['Musket (d8 B)', 'Sword (d6)', 'Flashbang'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby Arcana'
    },
    {
      equipment: ['Musket (d8 B)', 'Sword (d6)', 'Flashbang'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby Arcana'
    },
    {
      equipment: ['Musket (d8 B)', 'Sword (d6)', 'Flashbang'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby Arcana'
    },
    {
      equipment: ['Musket (d8 B)', 'Sword (d6)', 'Flashbang'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby Arcana'
    },
    {
      equipment: ['Musket (d8 B)', 'Sword (d6)', 'Flashbang'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby Arcana'
    },
    {
      equipment: ['Musket (d8 B)', 'Sword (d6)', 'Flashbang'],
      arcanum: false,
      companion: '',
      specialInformation: 'Sense nearby Arcana'
    },
    {
      equipment: ['Musket (d8 B)', 'Hatchet (d6)'],
      arcanum: true,
      companion: 'Hawk',
      specialInformation: ''
    },
    {
      equipment: ['Hatchet (d6)', 'Pistol (d6)', 'Bolt-Cutters'],
      arcanum: true,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Musket (d8 B)'],
      arcanum: true,
      companion: 'Mule',
      specialInformation: ''
    },
    {
      equipment: ['Sword (d6)', 'Pistol (d6)', 'Crude Armour'],
      arcanum: false,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Pistol (d6)', 'Bell', 'Steel Wire', 'Smoke-bomb'],
      arcanum: false,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Longaxe (d8 B)', 'Ferret', 'Fire Oil'],
      arcanum: false,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Staff (d6 B)', 'Tongs', 'Glue'],
      arcanum: false,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Pistol (d6)', 'Net', 'Trumpet'],
      arcanum: false,
      companion: '',
      specialInformation: 'Prosthetic Leg'
    },
    {
      equipment: ['Pistol (d6)', 'Grease', 'Hacksaw'],
      arcanum: false,
      companion: '',
      specialInformation: 'One Arm'
    }
  ],
  // 3 HP
  [
    {
      equipment: ['Musket (d8 B)', 'Club (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Immunity to extreme heat and cold',
    },
    {
      equipment: ['Musket (d8 B)', 'Club (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Immunity to extreme heat and cold',
    },
    {
      equipment: ['Musket (d8 B)', 'Club (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Immunity to extreme heat and cold',
    },
    {
      equipment: ['Musket (d8 B)', 'Club (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Immunity to extreme heat and cold',
    },
    {
      equipment: ['Musket (d8 B)', 'Club (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Immunity to extreme heat and cold',
    },
    {
      equipment: ['Musket (d8 B)', 'Club (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Immunity to extreme heat and cold',
    },
    {
      equipment: ['Musket (d8 B)', 'Club (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Immunity to extreme heat and cold',
    },
    {
      equipment: ['Musket (d8 B)', 'Protective Gloves'],
      arcanum: true,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Musket (d8 B)', 'Mallet', 'Marbles', 'Fancy Hat'],
      arcanum: true,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Pick-Axe (d6)', 'Manacles'],
      arcanum: true,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Pistol (d6)', 'Smoke-bomb', 'Shovel'],
      arcanum: false,
      companion: 'Mutt',
      specialInformation: '',
    },
    {
      equipment: ['Longaxe (d8 B)', 'Throwing Axes', 'Fire Oil'],
      arcanum: false,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Club (d6)', 'Ether', 'Crowbar', 'Flute'],
      arcanum: false,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Hatchet (d6)', 'Net', 'Fire Oil'],
      arcanum: false,
      companion: '',
      specialInformation: 'Burnt Face',
    },
    {
      equipment: ['Club (d6)', 'Paint', 'Crowbar'],
      arcanum: false,
      companion: '',
      specialInformation: 'Loud Lungs',
    },
    {
      equipment: ['Pistol (d6)', 'Cigars', 'Poison'],
      arcanum: false,
      companion: 'Fugitive',
      specialInformation: '',
    },
  ],
  // 4 HP
  [
    {
      equipment: ['Pistol (d6)', 'Knife (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Telepathy if target fails WIL Save',
    },
    {
      equipment: ['Pistol (d6)', 'Knife (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Telepathy if target fails WIL Save',
    },
    {
      equipment: ['Pistol (d6)', 'Knife (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Telepathy if target fails WIL Save',
    },
    {
      equipment: ['Pistol (d6)', 'Knife (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Telepathy if target fails WIL Save',
    },
    {
      equipment: ['Pistol (d6)', 'Knife (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Telepathy if target fails WIL Save',
    },
    {
      equipment: ['Pistol (d6)', 'Knife (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Telepathy if target fails WIL Save',
    },
    {
      equipment: ['Pistol (d6)', 'Knife (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: 'Telepathy if target fails WIL Save',
    },
    {
      equipment: ['Claymore (d8 B)', 'Pistol (d6)', '2 Acid Flasks'],
      arcanum: true,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Musket (d8 B)', 'Bayonet (d6)'],
      arcanum: false,
      companion: 'Mutt with telepathic link',
      specialInformation: '',
    },
    {
      equipment: ['Pistol (d6)', 'Rocket'],
      arcanum: false,
      companion: '',
      specialInformation: 'Toxin-Immune',
    },
    {
      equipment: ['Musket (d8 B)', 'Portable Ram', 'Game Set'],
      arcanum: false,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Pistol (d6)', 'Saw', 'Animal Trap', 'Spyglass'],
      arcanum: false,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Bow (d6 B)', 'Knife (d6)', 'Rocket', 'Fire Oil'],
      arcanum: false,
      companion: '',
      specialInformation: '',
    },
    {
      equipment: ['Pistol (d6)', 'Whip (d6)', 'Cigars'],
      arcanum: false,
      companion: '',
      specialInformation: 'Lost Eye',
    },
    {
      equipment: ['Musket (d8 B)', 'Accordion.'],
      arcanum: false,
      companion: '',
      specialInformation: 'No Nose/Scent',
    },
    {
      equipment: ['Sword (d6)', 'Shield'],
      arcanum: false,
      companion: '',
      specialInformation: 'Illiterate',
    },
  ],
  // 5 HP
  [
    {
      equipment: ['Blunderbuss (d8 B)', 'Hatchet (d6)'],
      arcanum: false,
      companion: 'Mutt',
      specialInformation: 'Dreams show your undiscovered surroundings'
    },
    {
      equipment: ['Blunderbuss (d8 B)', 'Hatchet (d6)'],
      arcanum: false,
      companion: 'Mutt',
      specialInformation: 'Dreams show your undiscovered surroundings'
    },
    {
      equipment: ['Blunderbuss (d8 B)', 'Hatchet (d6)'],
      arcanum: false,
      companion: 'Mutt',
      specialInformation: 'Dreams show your undiscovered surroundings'
    },
    {
      equipment: ['Blunderbuss (d8 B)', 'Hatchet (d6)'],
      arcanum: false,
      companion: 'Mutt',
      specialInformation: 'Dreams show your undiscovered surroundings'
    },
    {
      equipment: ['Blunderbuss (d8 B)', 'Hatchet (d6)'],
      arcanum: false,
      companion: 'Mutt',
      specialInformation: 'Dreams show your undiscovered surroundings'
    },
    {
      equipment: ['Blunderbuss (d8 B)', 'Hatchet (d6)'],
      arcanum: false,
      companion: 'Mutt',
      specialInformation: 'Dreams show your undiscovered surroundings'
    },
    {
      equipment: ['Blunderbuss (d8 B)', 'Hatchet (d6)'],
      arcanum: false,
      companion: 'Mutt',
      specialInformation: 'Dreams show your undiscovered surroundings'
    },
    {
      equipment: ['Brace of Pistols (d8 B)', 'Steel Wire', 'Grappling Hook'],
      arcanum: true,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Machete (d6)', 'Brace of Pistols (d8 B)'],
      arcanum: false,
      companion: 'Talking Parrot',
      specialInformation: 'Never Sleep'
    },
    {
      equipment: ['Harpoon Gun (d8 B)', 'Baton (d6)', 'Acid'],
      arcanum: false,
      companion: '',
      specialInformation: 'Slightly Magnetic'
    },
    {
      equipment: ['Bolt-Cutters', 'Blunderbuss (d8 B)', 'Fiddle'],
      arcanum: false,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Pistol (d6)', 'Grease', 'Hand Drill', 'Drum'],
      arcanum: false,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Sword & Dagger (d8 B)', 'Magnifying Glass'],
      arcanum: false,
      companion: '',
      specialInformation: 'Lost Eye'
    },
    {
      equipment: ['Pistol (d6)', 'Acid', 'Animal Repellent'],
      arcanum: false,
      companion: '',
      specialInformation: 'Prosthetic Hand'
    },
    {
      equipment: ['Sword (d6)', 'Steel Wire'],
      arcanum: false,
      companion: '',
      specialInformation: 'Ugly Mutation'
    },
    {
      equipment: ['Sword (d6)', 'Tattered Clothes'],
      arcanum: false,
      companion: 'Ferret',
      specialInformation: 'Debt (3G)'
    }
  ],
  // 6 HP
  [
    {
      equipment: ['Musket (d8 B)', 'Hatchet (d6)', 'Flashbang'],
      arcanum: true,
      companion: '',
      specialInformation: 'Iron Limb'
    },
    {
      equipment: ['Musket (d8 B)', 'Hatchet (d6)', 'Flashbang'],
      arcanum: true,
      companion: '',
      specialInformation: 'Iron Limb'
    },
    {
      equipment: ['Musket (d8 B)', 'Hatchet (d6)', 'Flashbang'],
      arcanum: true,
      companion: '',
      specialInformation: 'Iron Limb'
    },
    {
      equipment: ['Musket (d8 B)', 'Hatchet (d6)', 'Flashbang'],
      arcanum: true,
      companion: '',
      specialInformation: 'Iron Limb'
    },
    {
      equipment: ['Musket (d8 B)', 'Hatchet (d6)', 'Flashbang'],
      arcanum: true,
      companion: '',
      specialInformation: 'Iron Limb'
    },
    {
      equipment: ['Musket (d8 B)', 'Hatchet (d6)', 'Flashbang'],
      arcanum: true,
      companion: '',
      specialInformation: 'Iron Limb'
    },
    {
      equipment: ['Musket (d8 B)', 'Hatchet (d6)', 'Flashbang'],
      arcanum: true,
      companion: '',
      specialInformation: 'Iron Limb'
    },
    {
      equipment: ['Rifle (d8 B)', 'Mace (d6)', 'Eagle'],
      arcanum: false,
      companion: 'Poison',
      specialInformation: ''
    },
    {
      equipment: ['Club (d6)', '3 Bombs', 'Rocket'],
      arcanum: false,
      companion: '',
      specialInformation: 'Darkvision'
    },
    {
      equipment: ['Maul (d8 B)', 'Dagger (d6)', 'Chain'],
      arcanum: false,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Longaxe (d8 B)', 'Rum', 'Bomb'],
      arcanum: false,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Dagger (d6)', 'Fire Oil', 'Mirror'],
      arcanum: false,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Pistol (d6)', 'Knife (d6)', 'Bomb', 'Saw'],
      arcanum: false,
      companion: '',
      specialInformation: 'Glowing Eyes'
    },
    {
      equipment: ['Pistol (d6)', 'Bomb', 'Shovel'],
      arcanum: false,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Staff (d6 B)', 'Throwing Knives (d6)'],
      arcanum: false,
      companion: '',
      specialInformation: ''
    },
    {
      equipment: ['Mace (d6)'],
      arcanum: false,
      companion: 'Pigeon',
      specialInformation: 'Disfigured'
    }
  ]
];

export const arcanum = [
  {name: 'Gatekeeper\’s Sigil', description: 'Create a gate between two flat surfaces that you can see. The gates close if you pass through or break line of sight.'},
  {name: 'Pierced Heart', description: 'State an object you desire. The heart indicates its direction and vague distance.'},
  {name: 'Pale Flame', description: 'An object you touch glows with white light. Contact with the glowing object causes a chilling pain. The effect wears off when the Arcanum is used again.'},
  {name: 'Soul Chain', description: 'Target must pass a deX Save to avoid your touch, or they lose d6 WIL and you get a glimpse of their current desire.'},
  {name: 'The Unbreakable Seal', description: 'One door, window, etc. is sealed until you open it.'},
  {name: 'Foul Censer', description: 'Green smoke surrounds you and everyone within 20ft. Missiles cannot pass through the smoke.'},
  {name: 'Bleeding Stave', description: 'Spews blood-like oil onto a 10ft area. Anyone moving or standing on the oil must make a deX Save to avoid falling and being unable to move on their turn. Disappears in a harmless flash if ignited.'},
  {name: 'Pain Idol', description: 'Roll a die of your choice. If the result is odd, you lose that much stR, if it\’s even your target loses that much stR.'},
  {name: 'Webbed Hands', description: 'Climb sheer surfaces as if you were a spider.'},
  {name: 'Sunblessed Bands', description: 'Glow and hum lightly. Anybody attacking you suffers Damage equal to that they cause to you. If you attack a target yourself then the effect ends until you Rest.'},
  {name: 'Flesh-Tome of Babble', description: 'Speak in a strange sounding language. Every living thing is able to understand and reply in the same tongue if they wish.'},
  {name: 'Tyrant\’s Rod', description: 'Order a target to drop, fall, flee or halt unless they pass a WIL Save.'},
  {name: 'Black Veil', description: 'Target must pass a WIL Save or is blinded until you lift the curse or they Rest. Blinded individuals may require a deX Save to carry out other actions that rely on sight, and their attacks are Impaired.'},
  {name: 'Strands of Suffering', description: 'Strands spread between two surfaces up to 20ft apart. Those within only move very slowly and painfully unless they pass a deX Save.'},
  {name: 'Heat Ray', description: 'One metal object becomes too hot to touch. If it cannot be quickly dropped or removed the wielder suffers d8 Damage, ignoring armour.'},
  {name: 'Miniaturisation Coil', description: 'Touch an object to shrink it into a tiny miniature. Restore the object to original size at will. The original object can be up to your size, but living beings must be willing.'},
  {name: 'Frozen Cloud', description: 'Floats at your will. Anybody within takes d6 Damage and cannot move unless they pass a stR Save.'},
  {name: 'Many Phase Key', description: 'Phase through a wall or floor with any objects you are carrying.'},
  {name: 'Skull Magnet', description: 'You may attract or repel a single target that has a boney skull, unless they pass a WIL Save.'},
  {name: 'Transreal Mirror', description: 'A perfect duplicate of you is formed. It acts independently, and just like the original. It cannot interact physically with anything. The double lasts until dismissed or a new double is created.'},
  {name: 'Gorger\’s Mask', description: 'The wearer can consume anything safely.'},
  {name: 'Tomb Box', description: 'Contains three tiny skeletons that obey whoever holds the box. They are too small to do any real damage, but are quite agile and clever.'},
  {name: 'Howling Lantern', description: 'Blowing into the lantern causes a roar that terrifies prey animals, but attracts predators.'},
  {name: 'Rainbow Blade', description: 'This sword (d6) can fire a beam of harmless light in any colour the wielder wishes.'},
  {name: 'Hawk of Prosperity', description: 'A mechanical bird (3hp, d6 claws) that will only help you to accumulate wealth. Requires a Shilling each day as food.'},
  {name: 'Inquisitor\’s Hood', description: 'Speak a question with two possible answers. The target must pass a WIL Save or answer as honestly as they can. If they pass their Save you blurt out an inconvenient truth.'},
  {name: 'Winter\’s Sickle', description: 'Anybody taking Damage from this Sickle (d6) is Deprived and feels cold to their bones until they spend at least an hour warming themselves by a fire or other heat source.'},
  {name: 'Grief Cup', description: 'Anybody drinking from this cup has upsetting visions showing the consequences of their past actions.'},
  {name: 'Victory Globe', description: 'Swear an oath aloud. The globe gently guides you in the direction that would help you achieve the oath, but if you fail to complete it before the end of the day it lashes your mind for d12 WIL loss.'},
  {name: 'Moon Lens', description: 'Look at two objects and ask a question. The lens highlights the one object that best answers the question. It cannot predict the future.'},
  {name: 'Fool\’s Coin', description: 'Anybody that values money will crave this coin the first time they see it. The effect wears off after an hour.'},
  {name: 'Chance Rose', description: 'Crush this ceramic rose to change the odds of success for a single action to 50%. This cannot make the impossible possible. The rose reforms at the start of each day.'},
  {name: 'Homing Stick', description: 'A staff that can be called to return to you, flying by the best route possible.'},
  {name: 'False Platter', description: 'Anybody viewing this platter sees an illusion of luxury that they are craving right now.'},
  {name: 'Gold Visor', description: 'While wearing this you visualise a general sense of somebody\’s honesty and sincerity while they speak.'},
  {name: 'Infinity Icon', description: 'You can stop time, but you can do nothing but observe and think during this time.'},
];

export let greaterArcanum = [
  {name: 'Hypno-Torch', description: 'Target repeats their current action until you say stop, or they pass the Save on their turn.'},
  {name: 'Inferno Device', description: 'Cause a source of fire to explode, causing d10 Damage to all within 20ft.'},
  {name: 'Power Leech', description: 'Target must pass a WIL Save, or else you swap stR scores with them. Either side returns their stR to its original value when they Rest.'},
  {name: 'Fire Blooded Scroll', description: 'Target feels their blood begin to boil. They take d6 Damage, ignoring armour, each round, until they pass the Save.'},
  {name: 'Mind Probe', description: 'You are able to dig into the innermost thoughts of the target. They may pass a WIL Save to resist.'},
  {name: 'Book of Despair', description: 'Summon a 20ft area of tentacles that lash out and grab. Anyone within must pass a stR Save to break free. The mass of tentacles has 10hp and is destroyed at 0hp.'},
  {name: 'Primal Flute', description: 'All within 15ft must pass a WIL Save or turn feral. They do nothing but attack the nearest living thing until they pass a WIL Save on their turn.'},
  {name: 'Window to Beyond', description: 'Summon a flying beast (stR 14, 10hp, d8 Damage) to fight for you until no enemies remain. After this, you must pass a WIL Save or the beast turns on you. If you pass the Save, it flies for freedom. Only one beast can be summoned at once.'},
  {name: 'Black Orb', description: 'Obliterate a man-sized or smaller object you touch. No effect on living tissue.'},
  {name: 'Snakebite Parasite', description: 'Bite a target, for d6 Damage. You both lose d12 deX as the venom flows through you.'},
  {name: 'Horned Mask', description: 'You take on a bestial form (Armour 1, d10 Damage claws, retain Ability Scores and hp), but lose the ability to speak. Return to normal form when you sleep.'},
  {name: 'Doom Hive', description: '20ft buzzing cloud moves 10ft away from you each round. Anyone within loses d6 stR every round.'},
  {name: 'Withering Glove', description: 'Target must pass a stR Save or shrink to a husk. They halve their stR score (rounding up) and have all attacks Impaired. A Long Rest restores them to full size.'},
  {name: 'Spirit Cup', description: 'Swap bodies with another that drinks from the cup. They can resist with a WIL Save. Retain WIL scores only.'},
  {name: 'Entropy Crystal', description: 'Fires an unerring beam. Target must pass a stR Save or lose d12 deX. If this reduces their deX to zero they are turned to blue crystal.'},
  {name: 'Guardian\’s Shield', description: 'A shield of light appears between you and a single target. The shield absorbs 10 points of Damage before vanishing. Each turn it pushes the target 10ft away from you unless they pass a stR Save.'},
  {name: 'Earth Stone', description: 'Over an hour you shift sand, soil or earth to your will, creating ditches up to 10ft deep. This may destabilise structures, redirect rivers and fell trees but does not affect rock, create tunnels, or move fast enough to bury mobile opponents.'},
  {name: 'Roaring Lion', description: 'Glass, crystal or ceramic objects within 5ft are shattered. In addition, one object you are touching (wielder may avoid with a WIL Save) is shattered. This object must be light enough for you to lift.'},
  {name: 'Pressure Needle', description: 'If the target takes Critical Damage today they explode in a bloody mess.'},
  {name: 'Orb Box', description: 'Summon two orbs of light that obey your commands. They can be flung at a target for d12 Damage, destroying the orb. No more than two orbs can be summoned each day.'}
];
  
export const legendaryArcanum = [
  {name: 'Weather Altar', description: 'Cause the weather within a mile radius to change for the rest of the day. In the case of dangerous weather, you cannot target specific individuals or locations, or cause extremes that are inescapably lethal.'},
  {name: 'Obliteration Prism', description: 'Choose a target and roll d12. If this is equal or higher than their current hp they are completely destroyed in a blast of fire.'},
  {name: 'Rebirth Coffin', description: 'A corpse is miraculously restored to life if they pass a WIL Save. If they fail the Save, the remains are utterly destroyed.'},
  {name: 'Space Cube', description: 'You and up to one companion are teleported to a location you have been to before.'},
  {name: 'Malice Gong', description: 'All enemies within 20ft lose d6 stR.'},
  {name: 'Essence Projector', description: 'Conjures a ghostly image of a dead target, which speaks with you clearly and willingly, regardless of language or intelligence. The image remains until dismissed.'},
  {name: 'Seal of Madness', description: 'Creates symbols on any object. Anyone trying to decode them loses d12 WIL.'},
  {name: 'Quake Spire', description: 'Targets a 100ft area. All structures take d20 Damage and caves or tunnels collapse, causing d6 Damage per round to anyone within, until they escape.'},
  {name: 'Tablet of the Master', description: 'A large object is animated and serves you. The object has 10hp, Armour 2, and attacks for d10 Damage. No more than one object can serve you at once.'},
  {name: 'Forcefield Generator', description: 'Create a semi-transparent, shimmering surface that only you may pass through. Any enemy approaching the wall is blasted with light for d12 Damage. The field lasts until dismissed or another field is created.'},
  {name: 'Iron Suit', description: 'You have Armour 3 and ignore fire and poison based Damage. You can no longer swim but also do not need to breathe, eat or drink. The effect lasts until dismissed.'},
  {name: 'Dead Oak', description: 'Creates a permanent one-mile zone where any living things lose d6 stR each hour, starting at the end of this hour. Living things within this zone are instantly aware of this and try to leave. Even plants wither and die.'},
  {name: 'Forge of Reconstruction', description: 'Over an hour one damaged or ruined structure, ship or similar target is repaired to peak condition without need for materials.'},
  {name: 'Statue of the Golden Chariot', description: 'You and your allies fight to the death, even after taking Critical Damage.'},
  {name: 'Divine Pool', description: 'You take on the appearance of a huge, godlike entity. You can conjure purely cosmetic, but impressive, visual effects.'},
  {name: 'Storm Throne', description: 'You turn into a bolt of lightning, moving at impossible speed to a specified location you can see. Anyone you pass through takes d10 Damage, ignoring armour.'},
  {name: 'Transformation Cave', description: 'You shift to take the form of your chosen enemy, retaining only your WIL score and level of intelligence. This lasts until dismissed.'},
  {name: 'Black Hole Collider', description: 'Create a five-foot, black sphere. Anything entering it is utterly destroyed. Cannot be moved or placed on top of an object or opponent.'},
  {name: 'Mind Wiper', description: 'Target must pass a WIL Save or become a mindless automaton.'},
  {name: 'Starbeam Panel', description: 'As long as you have line of sight to the sky, you call down a column of light for d20 Damage.'}
];

export const names = [
  'The Usurper Quietus',
  'Hermes the Thrice Great',
  'Seven Against Thebes',
  'The Knave of Hearts',
  'Prisoner 46664',
  'Imperious Rex',
  'Calamity of the Ages',
  'Klaatu Barada Nikto',
  'Magnificent Faust',
  'Casus Belli',
  'Hungry is the Beast',
  'The Inconstant Man'
];

export const companionNames = [
  'Centurion',
  'Ajax',
  'Audacious',
  'George',
  'Caesar',
  'Hannibal',
  'Illustrious',
  'Jupiter',
  'Magnificent',
  'Majestic',
  'Mars',
  'Victorious'
];

export const items = [
  {
    category: 'Hand Weapon',
    name: 'Sword',
    description: 'Classic.',
    slots: 1,
    number: 0,
    damage: 6,
    armour: 0,
    cost: '2S'
  },
  {
    category: 'Hand Weapon',
    name: 'Dagger',
    description: 'Silent but deadly. Can be thrusted or thrown.',
    slots: 1,
    number: 0,
    damage: 6,
    armour: 0,
    cost: '2S'
  },
  {
    category: 'Hand Weapon',
    name: 'Pistol',
    description: 'A flintlock can be loaded and fired in 20 seconds.',
    slots: 1,
    number: 0,
    damage: 6,
    armour: 0,
    cost: '2S'
  },
  {
    category: 'Hand Weapon',
    name: 'Baton',
    description: 'Mad of wood, commonly used by militia.',
    slots: 1,
    number: 0,
    damage: 6,
    armour: 0,
    cost: '2S'
  },
  {
    category: 'Field Weapon',
    name: 'Musket',
    description: '6ft long and can be loaded with shot or ball.',
    slots: 1,
    number: 0,
    damage: 8,
    armour: 0,
    cost: '10S'
  },
  {
    category: 'Field Weapon',
    name: 'Brace of Pistols',
    description: 'A two-handed assault tactic.',
    slots: 1,
    number: 0,
    damage: 8,
    armour: 0,
    cost: '10S'
  },
  {
    category: 'Field Weapon',
    name: 'Halberd',
    description: 'An axe on a pole. Very versatile.',
    slots: 1,
    number: 0,
    damage: 8,
    armour: 0,
    cost: '10S'
  },
  {
    category: 'Field Weapon',
    name: 'Rapier and Dagger',
    description: 'A classic combination. The nmain-gauche is used for parrying.',
    slots: 1,
    number: 0,
    damage: 8,
    armour: 0,
    cost: '10S'
  },
  {
    category: 'Modern Armour',
    name: 'Cuirass',
    description: 'Chestplate and back piece, weighing in excess of 10lbs.',
    slots: 1,
    bulky: false,
    number: 0,
    damage: 0,
    armour: 1,
    cost: '50S'
  },
  {
    category: 'Modern Armour',
    name: 'Helm',
    description: 'The pot helmet or morion is standard issue in most modern armies.',
    slots: 1,
    bulky: false,
    number: 0,
    damage: 0,
    armour: 1,
    cost: '50S'
  },
  {
    category: 'Modern Armour',
    name: 'Buckler',
    description: 'Often combined with a rapier or sword, it can be used in defence and offence.',
    slots: 1,
    bulky: false,
    number: 0,
    damage: 0,
    armour: 1,
    cost: '50S'
  },
  {
    category: 'Explosive',
    name: 'Grenade',
    description: 'Cricket ball sized bomb, filled with black powder, used by grenadiers.',
    slots: 1,
    number: 0,
    damage: 10,
    armour: 0,
    cost: '20S'
  },
  {
    category: 'Explosive',
    name: 'Rocket',
    description: 'A grenade on a stick.',
    slots: 1,
    number: 0,
    damage: 10,
    armour: 0,
    cost: '20S'
  },
  {
    category: 'Explosive',
    name: 'Smoke-bomb',
    description: 'Combustable device that causes confusion. Attacks through the smoke are Impaired.',
    slots: 1,
    number: 0,
    damage: 10,
    armour: 0,
    cost: '20S'
  },
  {
    category: 'Explosive',
    name: 'Flashbang',
    description: 'Momentarily blinds anyone that fails a DEX Save.',
    slots: 1,
    number: 0,
    damage: 10,
    armour: 0,
    cost: '20S'
  },
  {
    category: 'Chemical',
    name: 'Poison',
    description: 'Lose 20 STR if consumed.',
    slots: 1,
    number: 0,
    damage: 20,
    armour: 0,
    cost: '10S'
  },
  {
    category: 'Chemical',
    name: 'Acid',
    description: 'D6 Damage, burns through most materials.',
    slots: 1,
    damage: 20,
    armour: 0,
    cost: '10S'
  },
  {
    category: 'Medicine',
    name: 'Antitoxin',
    description: 'Neutralises most toxins.',
    slots: 1,
    number: 0,
    damage: 0,
    armour: 0,
    cost: '10S'
  },
  {
    category:'Tool',
    name: 'Pitchfork',
    description: 'Useful for hunting witches.',
    name: 'Barstool',
    description: 'Would not be my weapon of choice, but will do in a pinch.',
    name: 'Rake',
    description: 'Especially potent versus demons.',
    name: 'Lockpicks',
    description: 'Can open most doors and padlocks.',
    slots: 1,
    number: 0,
    damage: 6,
    armour: 0,
    cost: '1S'
  },
  {
    category:'Tool',
    name: 'Barstool',
    description: 'Would not be my weapon of choice, but will do in a pinch.',
    slots: 1,
    number: 0,
    damage: 6,
    armour: 0,
    cost: '1S'
  },
  {
    category:'Tool',
    name: 'Rake',
    description: 'Especially potent versus demons.',
    slots: 1,
    number: 0,
    damage: 6,
    armour: 0,
    cost: '1S'
  },
  {
    category:'Tool',
    name: 'Lockpicks',
    description: 'Can open most doors and padlocks.',
    slots: 1,
    number: 0,
    damage: 0,
    armour: 0,
    cost: '1S'
  },
  {
    category: 'Loot',
    name: 'Elaborate Fashion',
    description: 'Fine tailored clothing.',
    slots: 1,
    number: 0,
    damage: 0,
    armour: 0,
    cost: '10S'
  },
];

// Tables from the rulebook.

const boroughCouncilDecisions = [
  { number: 1, councilAction: 'All Arcana must be registered' },
  { number: 2, councilAction: 'War with all other cities' },
  { number: 3, councilAction: 'Major cult is outlawed' },
  { number: 4, councilAction: 'Entire borough to be flattened' },
  { number: 5, councilAction: 'Army conscription' },
  { number: 6, councilAction: 'New council-sanctioned cult' },
  { number: 7, councilAction: 'Animal census' },
  { number: 8, councilAction: 'All prisoners to be executed' },
  { number: 9, councilAction: 'All prisoners to be released' },
  { number: 10, councilAction: 'Launching a cosmic rocket' },
  { number: 11, councilAction: 'Double taxes' },
  { number: 12, councilAction: 'Random mass eviction' },
  { number: 13, councilAction: 'Total lockdown' },
  { number: 14, councilAction: 'Inquisition into possible rebellion' },
  { number: 15, councilAction: 'Entire council executed and replaced' },
  { number: 16, councilAction: 'Exodus to the Golden Lands' },
  { number: 17, councilAction: 'Underground crusade' },
  { number: 18, councilAction: 'Guns outlawed' },
  { number: 19, councilAction: 'Alcohol prohibited' },
  { number: 20, councilAction: 'Martial law' }
];

const generalPublicReaction = [
  { number: 1, reaction: 'Riots!' },
  { number: 2, reaction: 'Tomorrow we launch an uprising!' },
  { number: 3, reaction: 'Someone should do something!' },
  { number: 4, reaction: 'Don’t care' },
  { number: 5, reaction: 'They probably have a good reason...' },
  { number: 6, reaction: 'Well it’s about time!' }
];

const castOfThousandsNames = [
  { number: 1, forenameMale: 'Augost', forenameFemale: 'Augosta', surname: 'Allane' },
  { number: 2, forenameMale: 'Benedict', forenameFemale: 'Benedicta', surname: 'Bargroll' },
  { number: 6, forenameMale: 'Brin', forenameFemale: 'Brin', surname: 'Brunfield' },
  { number: 9, forenameMale: 'Chumwan', forenameFemale: 'Chumwan', surname: 'Chop' },
  { number: 10, forenameMale: 'Calahed', forenameFemale: 'Calahed', surname: 'Creed' },
  { number: 13, forenameMale: 'Dorren', forenameFemale: 'Dorren', surname: 'Dunbell' },
  { number: 16, forenameMale: 'Emmett', forenameFemale: 'Emma', surname: 'Eggler' },
  { number: 18, forenameMale: 'Felix', forenameFemale: 'Felora', surname: 'Fox' },
  { number: 20, forenameMale: 'Fred', forenameFemale: 'Freda', surname: 'Farsee' },
  { number: 23, forenameMale: 'Grobin', forenameFemale: 'Grobina', surname: 'Gill' },
  { number: 27, forenameMale: 'Gizard', forenameFemale: 'Giza', surname: 'Gullwin' },
  { number: 30, forenameMale: 'Helroff', forenameFemale: 'Helriel', surname: 'Huckle' },
  { number: 34, forenameMale: 'Istan', forenameFemale: 'Isti', surname: 'Horrican' },
  { number: 38, forenameMale: 'Ilmer', forenameFemale: 'Ilda', surname: 'Ingle' },
  { number: 40, forenameMale: 'Junas', forenameFemale: 'Julia', surname: 'Jongler' },
  { number: 43, forenameMale: 'Katsun', forenameFemale: 'Katsin', surname: 'Kross' },
  { number: 46, forenameMale: 'Lurpax', forenameFemale: 'Lunda', surname: 'Lix' },
  { number: 50, forenameMale: 'Litton', forenameFemale: 'Littona', surname: 'Lowbile' },
  { number: 54, forenameMale: 'Munfud', forenameFemale: 'Munfi', surname: 'Montane' },
  { number: 57, forenameMale: 'Narmun', forenameFemale: 'Nadya', surname: 'Nutbush' },
  { number: 60, forenameMale: 'Orren', forenameFemale: 'Orrena', surname: 'Olifant' },
  { number: 62, forenameMale: 'Podder', forenameFemale: 'Poddina', surname: 'Offenpot' },
  { number: 64, forenameMale: 'Peta', forenameFemale: 'Peta', surname: 'Ouze' },
  { number: 67, forenameMale: 'Picklow', forenameFemale: 'Pickelle', surname: 'Phile' },
  { number: 70, forenameMale: 'Quinn', forenameFemale: 'Quinn', surname: 'Parfait' },
  { number: 75, forenameMale: 'Rosher', forenameFemale: 'Roshel', surname: 'Regal' },
  { number: 77, forenameMale: 'Stellan', forenameFemale: 'Stella', surname: 'Stagger' },
  { number: 80, forenameMale: 'Samford', forenameFemale: 'Sambay', surname: 'Shark' },
  { number: 82, forenameMale: 'Tucker', forenameFemale: 'Tuckis', surname: 'Tumble' },
  { number: 84, forenameMale: 'Teevan', forenameFemale: 'Teeva', surname: 'Terrine' },
  { number: 86, forenameMale: 'Urntin', forenameFemale: 'Urna', surname: 'Underhog' },
  { number: 89, forenameMale: 'Varran', forenameFemale: 'Varin', surname: 'Upperill' },
  { number: 90, forenameMale: 'Volta', forenameFemale: 'Voltel', surname: 'Volfhole' },
  { number: 92, forenameMale: 'Weckster', forenameFemale: 'Weckin', surname: 'Vinifera' },
  { number: 94, forenameMale: 'Yurnak', forenameFemale: 'Yurna', surname: 'Yarn' },
  { number: 96, forenameMale: 'Zarm', forenameFemale: 'Zarma', surname: 'Zarrack' },
];

const castOfThousandsOccupation = [
  { number: 1, occupation: "Actor" },
  { number: 2, occupation: "Barge Pilot" },
  { number: 6, occupation: "Butler" },
  { number: 9, occupation: "Coffee House Host" },
  { number: 10, occupation: "Coal Miner" },
  { number: 13, occupation: "Dog Breeder" },
  { number: 16, occupation: "Engine Cleaner" },
  { number: 18, occupation: "Fist Fighter" },
  { number: 20, occupation: "Fishmonger" },
  { number: 23, occupation: "Gull-Catcher" },
  { number: 25, occupation: "Glue maker" },
  { number: 27, occupation: "Gunsmith" },
  { number: 30, occupation: "Gin-Maker" },
  { number: 34, occupation: "Hog-Slaughterer" },
  { number: 38, occupation: "Ivory Worker" },
  { number: 40, occupation: "Jeweler" },
  { number: 42, occupation: "Lower-Politician" },
  { number: 44, occupation: "Life Servant" },
  { number: 47, occupation: "Lamp-Lighter" },
  { number: 50, occupation: "Lesser-Noble" },
  { number: 54, occupation: "Mercenary" },
  { number: 57, occupation: "Newspaper Vendor" },
  { number: 60, occupation: "Octopus-Catcher" },
  { number: 63, occupation: "Oyster Seller" },
  { number: 65, occupation: "Perfumer" },
  { number: 67, occupation: "Professor" },
  { number: 70, occupation: "Prison Guard" },
  { number: 74, occupation: "Pie-Smith" },
  { number: 78, occupation: "Road Sweeper" },
  { number: 80, occupation: "Salt Farmer" },
  { number: 82, occupation: "Sweet-Maker" },
  { number: 84, occupation: "Trinket-Merchant" },
  { number: 86, occupation: "Tax Collector" },
  { number: 89, occupation: "Tunnel Digger" },
  { number: 90, occupation: "Whaler" },
  { number: 93, occupation: "Watchmaker" },
  { number: 96, occupation: "Watchman" },
  { number: 98, occupation: "Writer" },
  { number: 100, occupation: "Wigmaker" },
];

const castOfThousandsCapability = [
  { number: 1, capability: "Attention to Detail" },
  { number: 2, capability: "Boringly Dependable" },
  { number: 6, capability: "Best in the City" },
  { number: 9, capability: "Cheap and Dirty" },
  { number: 10, capability: "Charming and Oily" },
  { number: 13, capability: "Dabbler" },
  { number: 16, capability: "Expensive and Flashy" },
  { number: 18, capability: "Fair and Down to Earth" },
  { number: 20, capability: "Filthy but very cheap" },
  { number: 23, capability: "Great, but hated for it" },
  { number: 25, capability: "Good but Annoying" },
  { number: 27, capability: "Highly Artistic" },
  { number: 30, capability: "Hardly trained" },
  { number: 34, capability: "Inherited Family Trade" },
  { number: 38, capability: "Interested in new career" },
  { number: 40, capability: "Imposter" },
  { number: 42, capability: "Jealous of Better" },
  { number: 44, capability: "Rival" },
  { number: 47, capability: "Learning, still" },
  { number: 50, capability: "Loves the job" },
  { number: 54, capability: "Lazy and Greedy" },
  { number: 57, capability: "Money-Grabbing" },
  { number: 60, capability: "Moral, but not that good" },
  { number: 63, capability: "Only serves friends" },
  { number: 65, capability: "Old-Master-Trained" },
  { number: 67, capability: "Perfectionist" },
  { number: 70, capability: "Paragon of the Job" },
  { number: 74, capability: "Poor from bad business" },
  { number: 78, capability: "Retired from Injury" },
  { number: 80, capability: "Ruthless" },
  { number: 82, capability: "Sworn into Profession" },
  { number: 84, capability: "Silently dutiful" },
  { number: 86, capability: "Trained from Birth" },
  { number: 89, capability: "Trapped in Job" },
  { number: 90, capability: "Uncaring" },
  { number: 93, capability: "Unreliable Genius" },
  { number: 96, capability: "Wedded into Career" },
  { number: 98, capability: "Wasted Talent" },
  { number: 100, capability: "Warm and Friendly" },
];

const castOfThousandsManner = [
  { number: 1, manner: 'Attractive Dullard' },
  { number: 2, manner: 'Big Fat' },
  { number: 6, manner: 'Glutton' },
  { number: 10, manner: 'Beaky Bore' },
  { number: 11, manner: 'Creaky Elder' },
  { number: 13, manner: 'Childlike' },
  { number: 16, manner: 'Dashing Young Gun' },
  { number: 18, manner: 'Ethereal Beauty' },
  { number: 19, manner: 'Fails at Flirtatious' },
  { number: 20, manner: 'Flamboyant Charmer' },
  { number: 23, manner: 'Great Speaker' },
  { number: 25, manner: 'Greasy Toad' },
  { number: 28, manner: 'Gentle Giant' },
  { number: 31, manner: 'Hulking Brute' },
  { number: 34, manner: 'Hunchback' },
  { number: 35, manner: 'Harmless Dope' },
  { number: 40, manner: 'Intensely Creepy' },
  { number: 42, manner: 'Ill-Coloured and Thin' },
  { number: 44, manner: 'Jolly and Fat' },
  { number: 47, manner: 'Loads of Jewellery' },
  { number: 50, manner: 'Lots of Scars' },
  { number: 54, manner: 'No Nose' },
  { number: 57, manner: 'Nice but Dim' },
  { number: 60, manner: 'Naive Teenager' },
  { number: 63, manner: 'Old Sleaze' },
  { number: 65, manner: 'Pig-Faced' },
  { number: 67, manner: 'Plucky Little Thing' },
  { number: 70, manner: 'Powdered Wig' },
  { number: 74, manner: 'Quite Ugly' },
  { number: 78, manner: 'Rough as a Dog' },
  { number: 80, manner: 'Stocky Grunter' },
  { number: 82, manner: 'Stunted Growth' },
  { number: 84, manner: 'Straight-Laced' },
  { number: 86, manner: 'Towering Klutz' },
  { number: 89, manner: 'Unwashed Slob' },
  { number: 90, manner: 'Vapid Fashionista' },
  { number: 93, manner: 'Very Long Hair' },
  { number: 96, manner: 'Well-Bred Snob' },
  { number: 98, manner: 'Waif' },
  { number: 100, manner: 'Weird Head' }
];

const castOfThousandsConnection = [
  { number: 1, manner: "Aunt/Uncle" },
  { number: 2, manner: "Sibling" },
  { number: 6, manner: "Best Friend" },
  { number: 10, manner: "Owes Money" },
  { number: 11, manner: "Old Friend" },
  { number: 13, manner: "Common ancestry" },
  { number: 16, manner: "Platonic Love" },
  { number: 18, manner: "Admiration" },
  { number: 19, manner: "Parent" },
  { number: 20, manner: "Owed Money" },
  { number: 23, manner: "Acquaintance" },
  { number: 25, manner: "Common Benefactor" },
  { number: 28, manner: "Hatred" },
  { number: 31, manner: "Irritation" },
  { number: 34, manner: "Twin" },
  { number: 35, manner: "Spouse" },
  { number: 40, manner: "Guardian" },
  { number: 42, manner: "Lover" },
  { number: 44, manner: "Mentor" },
  { number: 47, manner: "Abuser" },
  { number: 50, manner: "Lust" },
  { number: 54, manner: "Distaste" },
  { number: 57, manner: "House-Share" },
  { number: 60, manner: "Former Colleagues" },
  { number: 63, manner: "School Friends" },
  { number: 65, manner: "Adopted Parent" },
  { number: 67, manner: "Unrequited Love" },
  { number: 70, manner: "Planning Murder" },
  { number: 74, manner: "Knows Secret" },
  { number: 78, manner: "Romantic Rivals" },
  { number: 80, manner: "Backhand Deal" },
  { number: 82, manner: "Criminal Enterprise" },
  { number: 84, manner: "Shared Trauma" },
  { number: 86, manner: "Jealousy" },
  { number: 89, manner: "Violent Hate" },
  { number: 90, manner: "Engaged" },
  { number: 93, manner: "Protector" },
  { number: 96, manner: "Playful Rivalry" },
  { number: 98, manner: "Rivals" },
  { number: 100, manner: "Former Enemies" },
];

const whateverHappenedToThem = [
  { number: 1, event: 'Arrested Wrongfully for Minor Crime' },
  { number: 2, event: 'Arrested Rightfully for Major Crime' },
  { number: 6, event: 'Became Addicted to an Exotic Drug' },
  { number: 8, event: 'Contracted a Terrible Disease' },
  { number: 10, event: 'Debt Collectors are Applying Pressure' },
  { number: 12, event: 'Died in an Uprising' },
  { number: 14, event: 'Died in Industrial Accident' },
  { number: 16, event: 'Found Long-Lost Relative' },
  { number: 18, event: 'Found (new) Love' },
  { number: 20, event: 'Found a Major Arcanum' },
  { number: 23, event: 'Found a Lesser Arcanum' },
  { number: 25, event: 'Getting (Re)Married' },
  { number: 27, event: 'Joined a Star Cult' },
  { number: 30, event: 'Joined a New Revolutionary Group' },
  { number: 34, event: 'House Collapsed' },
  { number: 38, event: 'Lost at Sea' },
  { number: 40, event: 'Lost Everything' },
  { number: 42, event: 'Lamp-Lighter Burnt Down House' },
  { number: 44, event: 'Left Bastion for the Deep Country' },
  { number: 47, event: 'Left Bastion for a Lesser City' },
  { number: 50, event: 'Murdered in the Street' },
  { number: 54, event: 'Murdered in their Bed' },
  { number: 57, event: 'Nice person has given them some juicy work' },
  { number: 60, event: 'Press-Ganged into Military' },
  { number: 63, event: 'Rumours of Criminal Activity' },
  { number: 65, event: 'Rumours of Abnormal Behaviour' },
  { number: 66, event: 'Saw weird things in the sky' },
  { number: 70, event: 'Saw horrible beasts in the street' },
  { number: 74, event: 'Saw a murder nearby' },
  { number: 78, event: 'Taken up Military Service' },
  { number: 80, event: 'Taken in an Orphan' },
  { number: 83, event: 'The Watch are harassing them' },
  { number: 84, event: 'Underground Weirdos Abducted Them' },
  { number: 86, event: 'Vanished in a Burst of Light' },
  { number: 89, event: 'Wandered into Underground, now missing' },
  { number: 90, event: 'Won a fortune by gambling' },
  { number: 93, event: 'Witnessed an Abduction into the night sky' },
  { number: 96, event: 'Went on a drinking binge' },
  { number: 98, event: 'Recklessly leapt into a Doomed Romance' },
  { number: 100, event: 'No Event Occurred' }
];

const whatIsThisStreetLike = [
  { number: 1, poi: 'Brewery', atmosphere: 'Welcoming', linkToUnderground: 'No' },
  { number: 2, poi: 'Meeting', atmosphere: 'Dark', linkToUnderground: 'Probably in the next road down' },
  { number: 6, poi: 'Fountain', atmosphere: 'Smoggy', linkToUnderground: 'No, and why are you so interested?' },
  { number: 9, poi: 'Restaurant', atmosphere: 'Abandoned', linkToUnderground: 'No, we don\'t want Weirdos coming up' },
  { number: 10, poi: 'Sunken Pit', atmosphere: 'Bustling', linkToUnderground: 'No, it\'s too dangerous to leave them open' },
  { number: 13, poi: 'Bar', atmosphere: 'Brightly Lit', linkToUnderground: 'Sure! Oh, wait, it\'s gone' },
  { number: 16, poi: 'Fighting Den', atmosphere: 'Creepy', linkToUnderground: 'Yes, but the tunnels are too hot to survive' },
  { number: 18, poi: 'Castle', atmosphere: 'Drafty', linkToUnderground: 'No, soldiers came and sealed it up' },
  { number: 20, poi: 'City Wall', atmosphere: 'Sinister', linkToUnderground: 'Yes, but it leads straight into an acid pool' },
  { number: 23, poi: 'Huge Factory', atmosphere: 'Comforting', linkToUnderground: 'Nobody wants to talk about the Underground' },
  { number: 27, poi: 'Coal Heap', atmosphere: 'Rat-Infested', linkToUnderground: 'We dug this one quite recently' },
  { number: 30, poi: 'Poorhouse', atmosphere: 'Expensive', linkToUnderground: 'An escape tunnel out of town' },
  { number: 34, poi: 'Public Baths', atmosphere: 'In Poverty', linkToUnderground: 'Yeah, an old trapdoor' },
  { number: 38, poi: 'Observatory', atmosphere: 'Dusty', linkToUnderground: 'A wine cellar leads somewhere horrible' },
  { number: 40, poi: 'University', atmosphere: 'Freshly Built', linkToUnderground: 'This tunnel goes right across town' },
  { number: 43, poi: 'Building Site', atmosphere: 'Ruined', linkToUnderground: 'A particularly disgusting sewer' },
  { number: 46, poi: 'Winding Alleyways', atmosphere: 'Burnt', linkToUnderground: 'An old bank vault' },
  { number: 50, poi: 'Shop Row', atmosphere: 'On Fire!', linkToUnderground: 'Smugglers have set up tunnels around here' },
  { number: 54, poi: 'Residential Terrace', atmosphere: 'Overrun by Rioters', linkToUnderground: 'They all got sealed up years ago' },
  { number: 57, poi: 'Botanical Garden', atmosphere: 'Bird Infested', linkToUnderground: 'There\'s a tunnel in plain sight' },
  { number: 60, poi: 'Cult Temple', atmosphere: 'Falling Down', linkToUnderground: 'Hidden stairway indoors' },
  { number: 62, poi: 'Docks', atmosphere: 'Ancient', linkToUnderground: 'A hole opened up last week' },
  { number: 64, poi: 'Warehouses', atmosphere: 'Artistic', linkToUnderground: 'Nasty things burst from the ground here' },
  { number: 67, poi: 'Underground Shelter', atmosphere: 'Eccentric', linkToUnderground: 'An old vault entrance' },
  { number: 70, poi: 'School', atmosphere: 'Physics-Defying', linkToUnderground: 'Emergency shelter nearby' },
  { number: 75, poi: 'Ironworks', atmosphere: 'Underground', linkToUnderground: 'Just a chute straight down' },
  { number: 77, poi: 'Canal Dock', atmosphere: 'Overgrown', linkToUnderground: 'Spiral staircase ornately decorated' },
  { number: 80, poi: 'Amusement Complex', atmosphere: 'Hidden', linkToUnderground: 'An overgrown natural cave' },
  { number: 82, poi: 'Specialist Shops', atmosphere: 'Criminal', linkToUnderground: 'Tunnel at the bottom of a pond' },
  { number: 84, poi: 'Bridge', atmosphere: 'Council-Sanctioned', linkToUnderground: 'Open sewer' },
  { number: 86, poi: 'Manor', atmosphere: 'Rebellious', linkToUnderground: 'An old well' },
  { number: 89, poi: 'Guild House', atmosphere: 'Protesting', linkToUnderground: 'Rusty ladder down a chute' },
  { number: 90, poi: 'Army Barracks', atmosphere: 'Cult-Linked', linkToUnderground: 'It caved in recently' },
  { number: 92, poi: 'Shopping Arcade', atmosphere: 'Dangerous', linkToUnderground: 'An old elevator' },
  { number: 94, poi: 'Watchtower', atmosphere: 'Filthy', linkToUnderground: 'A newly fitted elevator' },
  { number: 96, poi: 'City Watch Station', atmosphere: 'Overrun by Orphans', linkToUnderground: 'The hole where they throw their rubbish' },
  { number: 98, poi: 'Hospital', atmosphere: 'Fearful', linkToUnderground: 'Huge pit into the darkness' },
  { number: 100, poi: 'Cult Cathedral', atmosphere: 'Nonsensical', linkToUnderground: 'Tunnel at the bottom of the river' }
];

const theQuickestRouteAcrossTown = [
  { number: 1, route: 'Crawl-Tunnel' },
  { number: 2, route: 'Funicular' },
  { number: 6, route: 'Horse Carriage' },
  { number: 9, route: 'Underground Carriageway' },
  { number: 10, route: 'Canal Boat' },
  { number: 13, route: 'Underground Canal' },
  { number: 16, route: 'Shady Alleyways' },
  { number: 18, route: 'Straight Through the Park' },
  { number: 20, route: 'Along the Docks' },
  { number: 23, route: 'Rooftop Walkway' },
  { number: 25, route: 'Down the High Street' },
  { number: 27, route: 'Through a Riot' },
  { number: 30, route: 'Underground Tramway' },
  { number: 34, route: 'Tunnel with Toll Booth' },
  { number: 38, route: 'Hired Carriage' },
  { number: 40, route: 'Through an Abandoned Warehouse' },
  { number: 42, route: 'Through a Working Factory' },
  { number: 44, route: 'Through the Slums' },
  { number: 47, route: 'Through the Rich Neighbourhoods' },
  { number: 50, route: 'Along the City Walls' },
  { number: 54, route: 'Steamboat Down the River' },
  { number: 57, route: 'Hand Carriage' },
  { number: 60, route: 'Underground Tunnels' },
  { number: 63, route: 'Through the Market' },
  { number: 65, route: 'The Wine Cellar Network' },
  { number: 67, route: 'Catacombs' },
  { number: 70, route: 'Through the Old Town' },
  { number: 74, route: 'Urgh, Sewers' },
  { number: 78, route: 'Through the Bad End of Town' },
  { number: 80, route: 'Across University Campus' },
  { number: 82, route: 'Through the Botanical Gardens' },
  { number: 84, route: 'Along the Canals' },
  { number: 86, route: 'Over a Ruined Castle' },
  { number: 89, route: 'Through the Graveyard Quarter' },
  { number: 90, route: 'Up the Hill, then back down' },
  { number: 93, route: 'Right Through the Crazy Part of Town' },
  { number: 96, route: 'Through a Cult Temple' },
  { number: 98, route: 'Past the Army Barracks' },
  { number: 100, route: 'Through the Smuggler Tunnels' }
];

const IsThereALinkToUnderground = [
  { number: 1, answer: "No" },
  { number: 2, answer: "Probably in the next road down" },
  { number: 6, answer: "No, and why are you so interested?" },
  { number: 9, answer: "No, we don't want Weirdos coming up" },
  { number: 10, answer: "No, it's too dangerous to leave them open" },
  { number: 13, answer: "Sure! Oh, wait, it's gone" },
  { number: 16, answer: "Yes, but the tunnels are too hot to survive" },
  { number: 18, answer: "No, soldiers came and sealed it up" },
  { number: 20, answer: "Yes, but it leads straight into an acid pool" },
  { number: 23, answer: "Nobody wants to talk about the Underground" },
  { number: 25, answer: "We dug this one quite recently" },
  { number: 27, answer: "An escape tunnel out of town" },
  { number: 30, answer: "Yeah, an old trapdoor" },
  { number: 34, answer: "A wine cellar leads somewhere horrible" },
  { number: 38, answer: "This tunnel goes right across town" },
  { number: 40, answer: "A particularly disgusting sewer" },
  { number: 42, answer: "An old bank vault" },
  { number: 44, answer: "Smugglers have set up tunnels around here" },
  { number: 47, answer: "They all got sealed up years ago" },
  { number: 50, answer: "There's a tunnel in plain sight" },
  { number: 54, answer: "Hidden stairway indoors" },
  { number: 57, answer: "A hole opened up last week" },
  { number: 60, answer: "Nasty things burst from the ground here" },
  { number: 63, answer: "An old vault entrance" },
  { number: 65, answer: "Emergency shelter nearby" },
  { number: 67, answer: "Just a chute straight down" },
  { number: 70, answer: "Spiral staircase ornately decorated" },
  { number: 74, answer: "An overgrown natural cave" },
  { number: 78, answer: "Tunnel at the bottom of a pond" },
  { number: 80, answer: "Open sewer" },
  { number: 82, answer: "An old well" },
  { number: 84, answer: "Rusty ladder down a chute" },
  { number: 86, answer: "It caved in recently" },
  { number: 89, answer: "An old elevator" },
  { number: 90, answer: "A newly fitted elevator" },
  { number: 93, answer: "The hole where they throw their rubbish" },
  { number: 96, answer: "Huge pit into the darkness" },
  { number: 98, answer: "Tunnel at the bottom of the river" },
  { number: 100, answer: "Natural cave in somebody's cellar" },
];

const businesses = [
  { number: 1, name: "Cage-Brand Steam Generators" },
  { number: 2, name: "Pickem's Enterprise Loans" },
  { number: 6, name: "Anise Sisters Security" },
  { number: 9, name: "Gasman Spice & Soap" },
  { number: 10, name: "Prospective Telecoms" },
  { number: 13, name: "The Lady's Sugar and Coffeehouse" },
  { number: 16, name: "Yesser's Wool and Meat" },
  { number: 18, name: "Secure Properties and Jails" },
  { number: 20, name: "Consolidated Bookmakers" },
  { number: 23, name: "Commercial Voice Printed Press" },
  { number: 27, name: "Gallow, Sniff, & Pine Medical Research" },
  { number: 30, name: "Claymore Bank & Private Military" },
  { number: 34, name: "Broken Compass Offshore Acquisitions" },
  { number: 38, name: "Baker Arms & Munitions" },
  { number: 40, name: "Cohen Mass Nutrition Solutions" },
  { number: 43, name: "Footman Stills Spirits & Tonics" },
  { number: 46, name: "Braker's Streetlamp and Halberd" },
  { number: 50, name: "Black Horse Hospitals and Asylums" },
  { number: 54, name: "Bastio-Goldish Coal, Oil, and Ore" },
  { number: 57, name: "Confectioner's Village Foods & Homes" },
  { number: 60, name: "Red Ghost Roads & Carriages" },
  { number: 62, name: "Freeman Brewers & Bakers" },
  { number: 64, name: "Drake Ships & Sails" },
  { number: 67, name: "Shooman Boots & Tonics" },
  { number: 70, name: "Bates' Smoke Farms" },
  { number: 75, name: "Great Underground Disposal Company" },
  { number: 77, name: "Clock's Shippage & Canals" },
  { number: 80, name: "Hightower Hats & Canes" },
  { number: 82, name: "Territorial Tea & Wine" },
  { number: 84, name: "Outlander's Exotic Down & Fur" },
  { number: 86, name: "Furrupp's Brick & Mortar" },
  { number: 89, name: "Bitter & Snatch Jewellery" },
  { number: 90, name: "Werner's Industrial Machinery" },
  { number: 92, name: "Silvermountain Private Security" },
  { number: 94, name: "Aria Mines" },
  { number: 96, name: "Miracle Factory Ice & Salt" },
  { number: 98, name: "Metropolitan Tramway" },
  { number: 100, name: "Sunfair Gold Holdings" },
];

const weirdCreatures = [
  { number: 1, nature: "Solid-Smoke", form: "Cube", twist: "Mastery of Magnetism" },
  { number: 2, nature: "Skeletal", form: "Tripod", twist: "Grasps with Extra Limbs" },
  { number: 6, nature: "Decaying", form: "Swarm", twist: "Phases Through Matter" },
  { number: 9, nature: "Luxurious", form: "Disembodied Hand", twist: "Chimera (roll additional Form)" },
  { number: 10, nature: "Bio-Machine", form: "Worm", twist: "Reads Minds" },
  { number: 13, nature: "Living Construct", form: "Sphere", twist: "Colossal Size" },
  { number: 16, nature: "Reptilian", form: "Hound", twist: "Drains Life" },
  { number: 18, nature: "Slime Covered", form: "Great Cat", twist: "Sprays Acid" },
  { number: 20, nature: "Glassy", form: "Snake", twist: "Creates Black-Holes" },
  { number: 23, nature: "Liquid Metal", form: "Crustacean", twist: "Teleports Self" },
  { number: 27, nature: "Ceramic", form: "Squat Biped", twist: "Teleports Others" },
  { number: 30, nature: "Living Rock", form: "Slender Biped", twist: "Shifts Shape" },
  { number: 34, nature: "Scabs and Sores", form: "Insect", twist: "Breathes Smoke" },
  { number: 38, nature: "Hyper-Robotic", form: "Obese Biped", twist: "Creates Electric Charge" },
  { number: 40, nature: "Spiny", form: "Towering Biped", twist: "Sees Future" },
  { number: 43, nature: "Stinking Filth", form: "Baby Bird", twist: "Controls Others" },
  { number: 46, nature: "Shadow-Cloaked", form: "Slug", twist: "Cloaking Device" },
  { number: 50, nature: "Eerily Beautiful", form: "Snail", twist: "Conjures Illusions" },
  { number: 54, nature: "Mechanical Suit", form: "Hawk", twist: "Infects with Disease" },
  { number: 57, nature: "Sapient and Armoured", form: "Terror-Bird", twist: "Kills with Venom" },
  { number: 60, nature: "Baroque Excess", form: "Bull", twist: "Hunts Arcana" },
  { number: 62, nature: "Leathery", form: "Shark", twist: "Fires Bullets" },
  { number: 64, nature: "Feathered", form: "Spider", twist: "Freeze Matter" },
  { number: 67, nature: "Pale and Bald", form: "Blob", twist: "Heat/Melt Matter" },
  { number: 70, nature: "Ghostly", form: "Spiral", twist: "Implants with Egg/Parasite" },
  { number: 74, nature: "Holographic", form: "Pyramid", twist: "Paralyzes with Touch" },
  { number: 78, nature: "Hardlight", form: "Sheet", twist: "Fires Death Rays" },
  { number: 80, nature: "Acid Dripping", form: "Wasp", twist: "Manipulates Living Tissue Telekinetically" },
  { number: 82, nature: "Shaggy Hair", form: "Maggot", twist: "Manipulates Objects Telekinetically" },
  { number: 84, nature: "Mirrored Metal", form: "Tadpole", twist: "Sees Distant Places" },
  { number: 86, nature: "Damp Clay", form: "Jellyfish", twist: "Regenerates from any harm" },
  { number: 89, nature: "Colossal", form: "Bat", twist: "Reflects harm onto attacker" },
  { number: 90, nature: "Bare Musculature", form: "Octopus", twist: "Absorbs victims into Body" },
  { number: 92, nature: "All-Brain", form: "Pike", twist: "Turns victims into non-living matter" },
  { number: 94, nature: "Plasmic", form: "Sea Urchin", twist: "Launch explosives" },
  { number: 96, nature: "Chitin", form: "Cannon", twist: "Cause intense pain at touch" },
  { number: 98, nature: "Rusted Shell", form: "Fly", twist: "Heal any harm with a touch" },
  { number: 100, nature: "Bionic Parts", form: "Fetal", twist: "Sense distant objects" },
];

const astralCults = [
  { number: 1, collective: "Library", description: "Devouring", symbol: "Sword", standing: "Hated" },
  { number: 2, collective: "Children", description: "Kindly", symbol: "Snake", standing: "Hidden" },
  { number: 6, collective: "Fortress", description: "Dreaming", symbol: "Child", standing: "Disgraced" },
  { number: 9, collective: "Heralds", description: "Infinite", symbol: "Egg", standing: "Bankrupt" },
  { number: 10, collective: "Keepers", description: "Glowing", symbol: "Cloud", standing: "Disgusting" },
  { number: 13, collective: "Temple", description: "Dead", symbol: "Light", standing: "Outlawed" },
  { number: 16, collective: "Betrayers", description: "Rotting", symbol: "Star", standing: "Enemies of another Cult" },
  { number: 18, collective: "Hunters", description: "Raging", symbol: "Father", standing: "Tiny" },
  { number: 20, collective: "Union", description: "Golden", symbol: "Maw", standing: "Weak" },
  { number: 23, collective: "School", description: "Unborn", symbol: "Song", standing: "Fake" },
  { number: 27, collective: "Seekers", description: "Blessed", symbol: "Colour", standing: "Forgotten" },
  { number: 30, collective: "Knights", description: "Chained", symbol: "Gate", standing: "Nobody Cares" },
  { number: 34, collective: "Order", description: "Sunken", symbol: "Ship", standing: "Mocked" },
  { number: 38, collective: "Drinkers", description: "Broken", symbol: "Death", standing: "Discouraged" },
  { number: 40, collective: "Choir", description: "Stirring", symbol: "Sea", standing: "Hunted" },
  { number: 43, collective: "Sons", description: "Newborn", symbol: "Shadow", standing: "Weakened" },
  { number: 46, collective: "Daughters", description: "Golden", symbol: "Giants", standing: "Underground" },
  { number: 50, collective: "Servants", description: "Bloodied", symbol: "General", standing: "Unknown" },
  { number: 54, collective: "Society", description: "Half", symbol: "Truth", standing: "Hardly Known" },
  { number: 57, collective: "Army", description: "Forgotten", symbol: "Lie", standing: "Feared" },
  { number: 60, collective: "Wanderers", description: "Underground", symbol: "King", standing: "Taboo" },
  { number: 62, collective: "Pilgrims", description: "Twisted", symbol: "Queen", standing: "Too Old to Criticise" },
  { number: 64, collective: "Contemplators", description: "Glorious", symbol: "Force", standing: "Too Big to Fail" },
  { number: 67, collective: "Movement", description: "Vengeful", symbol: "Swarm", standing: "Somewhat Liked" },
  { number: 70, collective: "Preachers", description: "Laughing", symbol: "Fleet", standing: "Charitable" },
  { number: 75, collective: "Revolution", description: "Elder", symbol: "Horror", standing: "Tolerated" },
  { number: 77, collective: "Mercy-Givers", description: "Loving", symbol: "Beauty", standing: "Wealthy" },
  { number: 80, collective: "Council", description: "Undefeatable", symbol: "Spire", standing: "Sprawling" },
  { number: 82, collective: "Tower", description: "Timeless", symbol: "Crystals", standing: "Allies of another Cult" },
  { number: 84, collective: "Worshipers", description: "Striking", symbol: "Pantheon", standing: "Respected" },
  { number: 86, collective: "Observers", description: "Roaring", symbol: "Throne", standing: "Front for a Business" },
  { number: 89, collective: "Beggars", description: "Inevitable", symbol: "Web", standing: "Actively Recruiting" },
  { number: 90, collective: "Witnesses", description: "Bright", symbol: "Eye", standing: "Fashionable" },
  { number: 92, collective: "Centre", description: "Jade", symbol: "Hand", standing: "Strong" },
  { number: 94, collective: "Garrison", description: "Iron", symbol: "Shield", standing: "Powerful" },
  { number: 96, collective: "Engineers", description: "Bone", symbol: "Skull", standing: "Legendary" },
  { number: 98, collective: "Family", description: "Silent", symbol: "Weed", standing: "Beloved" },
  { number: 100, collective: "Chanters", description: "Pure", symbol: "Mist", standing: "Council-Sanctioned" },
];

const whatIsBeyondTheDarkeness = [
  { number: 1, feature: 'Weird Generator', hazard: 'Bell Alarm', spoils: 'Gilded Throne (30G)' },
  { number: 2, feature: 'Corpse Pit', hazard: 'Searing Hot Walls', spoils: 'Locked Chest (10G)' },
  { number: 6, feature: 'Abyssal Chasm', hazard: 'Glass Snakes', spoils: 'Glowing Rod (inanimate, 10S)' },
  { number: 9, feature: 'Labyrinth', hazard: 'Crawling Eyes', spoils: 'd6 Crocodile Eggs' },
  { number: 10, feature: 'Murder Shrine', hazard: 'Acid Puddles', spoils: 'Diamond Ring (2S)' },
  { number: 13, feature: 'Flowing Filth', hazard: 'Tunnel Shark', spoils: 'Looking Glass' },
  { number: 16, feature: 'Sealed Vault', hazard: 'Crushing Walls', spoils: 'Town Crier Bell' },
  { number: 18, feature: 'Bunker', hazard: 'Taunting Voices', spoils: 'Unnaturally Bright Lantern' },
  { number: 20, feature: 'Dirt Hole', hazard: 'Hidden Spikes', spoils: 'Opal Brooch (2S)' },
  { number: 23, feature: 'Crumbling Chapel', hazard: 'Slime Drones', spoils: 'Black Gem (1G)' },
  { number: 27, feature: 'Art Gallery', hazard: 'Carnivorous Birds', spoils: 'Telescope' },
  { number: 30, feature: 'Forge', hazard: 'Insane Babbling', spoils: 'Sack of Coal' },
  { number: 34, feature: 'Office', hazard: 'Insane Soldier', spoils: 'Symbolic Dagger' },
  { number: 38, feature: 'Torture Chamber', hazard: 'Deafening Siren', spoils: 'Astral Pistol' },
  { number: 40, feature: 'Feast Hall', hazard: 'Devouring Maw', spoils: 'Musket' },
  { number: 43, feature: 'Military Tomb', hazard: 'Grasping Tentacles', spoils: 'Wicker Ball' },
  { number: 46, feature: 'Ancient Barrow', hazard: 'Questioning Brain', spoils: 'Hammers and other Tools' },
  { number: 50, feature: 'Cult Catacomb', hazard: 'Huge Beast', spoils: 'Feathered Headband' },
  { number: 54, feature: 'Fighting Pit', hazard: 'Collapsing', spoils: 'Leather Bracers (falling apart)' },
  { number: 57, feature: 'Well', hazard: 'Floor Shifting', spoils: 'Flute (silver, 50S)' },
  { number: 60, feature: 'Drinking Hole', hazard: 'Illusions Stone', spoils: 'Huge Drum' },
  { number: 62, feature: 'Crystal Cave', hazard: 'Automatons', spoils: 'Blood Soaked Rags' },
  { number: 64, feature: 'Prison', hazard: 'Incineration Pit', spoils: 'Hand Mirror' },
  { number: 67, feature: 'Natural Spring', hazard: 'Living Chains', spoils: 'Audacious Painting' },
  { number: 70, feature: 'Open Vault', hazard: 'Cursing Hag', spoils: 'Metal Staff' },
  { number: 75, feature: 'Flooded Sewer', hazard: 'Frightened Cat', spoils: 'Set of Modern Armour' },
  { number: 77, feature: 'Abandoned Tramway', hazard: 'Holographic Spiders', spoils: 'Modern Armour' },
  { number: 80, feature: 'Gun Workshop', hazard: 'Gusts of Wind', spoils: 'Crude Armour' },
  { number: 82, feature: 'Gunpowder Store', hazard: 'Ghostly Hands', spoils: 'White Boulder' },
  { number: 84, feature: 'Dog Pit', hazard: 'Dust Tornadoes', spoils: 'Drinking Horn' },
  { number: 88, feature: 'Alchemy Lab', hazard: 'Acidic Ooze', spoils: 'Beast Tusk (50S)' },
  { number: 89, feature: 'Printing Press', hazard: 'Freeze-Rays', spoils: 'Glowing Sword (ignores Armour)' },
  { number: 90, feature: 'Metal Sphere', hazard: 'Shifting Blocks', spoils: 'Stone Tablet (gibberish)' },
  { number: 92, feature: 'Underground Lake', hazard: 'All-Seeing Eye', spoils: 'Engine Parts' },
  { number: 94, feature: 'Throne Room', hazard: 'Mechanical Judge', spoils: 'Anvil' },
  { number: 96, feature: 'Armoury', hazard: 'Angry Mutants', spoils: 'Dice (twelve-sided)' },
  { number: 98, feature: 'Swimming Pool', hazard: 'Rival Explorers', spoils: 'Glass Chains (oddly warm)' },
  { number: 100, feature: 'Observatory', hazard: 'Impenetrable Shadow', spoils: 'Cannon (in need of repair)' }
];

const spoils = [
  { number: 1, spoils: "Gilded Throne (30G)" },
  { number: 2, spoils: "Locked Chest (10G)" },
  { number: 6, spoils: "Glowing Rod (inanimate, 10S)" },
  { number: 9, spoils: "d6 Crocodile Eggs" },
  { number: 10, spoils: "Diamond Ring (2S)" },
  { number: 13, spoils: "Looking Glass" },
  { number: 16, spoils: "Town Crier Bell" },
  { number: 18, spoils: "Unnaturally Bright Lantern" },
  { number: 20, spoils: "Opal Brooch (2S)" },
  { number: 23, spoils: "Black Gem (1G)" },
  { number: 25, spoils: "Telescope" },
  { number: 27, spoils: "Sack of Coal" },
  { number: 30, spoils: "Symbolic Dagger" },
  { number: 34, spoils: "Astral Pistol" },
  { number: 38, spoils: "Musket" },
  { number: 40, spoils: "Wicker Ball" },
  { number: 42, spoils: "Hammers and other Tools" },
  { number: 44, spoils: "Feathered Headband" },
  { number: 47, spoils: "Leather Bracers (falling apart)" },
  { number: 50, spoils: "Flute (silver, 50S)" },
  { number: 54, spoils: "Huge Drum" },
  { number: 57, spoils: "Blood Soaked Rags" },
  { number: 60, spoils: "Hand Mirror" },
  { number: 63, spoils: "Audacious Painting" },
  { number: 65, spoils: "Metal Staff" },
  { number: 67, spoils: "Set of Modern Armour" },
  { number: 70, spoils: "Modern Armour" },
  { number: 74, spoils: "Crude Armour" },
  { number: 78, spoils: "White Boulder" },
  { number: 80, spoils: "Drinking Horn" },
  { number: 82, spoils: "Beast Tusk (50S)" },
  { number: 84, spoils: "Glowing Sword (ignores Armour)" },
  { number: 86, spoils: "Stone Tablet (gibberish)" },
  { number: 89, spoils: "Engine Parts" },
  { number: 90, spoils: "Anvil" },
  { number: 93, spoils: "Dice (twelve-sided)" },
  { number: 96, spoils: "Glass Chains (oddly warm)" },
  { number: 98, spoils: "Cannon (in need of repair)" },
  { number: 100, spoils: "Dead Dog" },
];

const whatIsThatIsland = [
  { number: 1, landmark: "Smoking Volcano", twist: "Island is Intelligent" },
  { number: 2, landmark: "Huge Waterfall", twist: "Sweltering Heat" },
  { number: 6, landmark: "Ice-Capped Peak", twist: "Covered by Metal Dome" },
  { number: 9, landmark: "Glittering Lake", twist: "Nobody Can Die Here" },
  { number: 10, landmark: "Colourful Lights", twist: "Sinking" },
  { number: 13, landmark: "Red Forests", twist: "Recently Resurfaced" },
  { number: 16, landmark: "Black Sands", twist: "Toxic Air" },
  { number: 18, landmark: "Rock Fortress", twist: "Utterly Silent" },
  { number: 20, landmark: "Abandoned Fleet", twist: "Plants Grow Visibly" },
  { number: 23, landmark: "Salt Beach", twist: "Eternal Night" },
  { number: 27, landmark: "Crystal Shards", twist: "Completely Abandoned" },
  { number: 30, landmark: "Absolutely Flat", twist: "Expedition Gone Native" },
  { number: 34, landmark: "Thorny Jungle", twist: "Giant Killer Frogs" },
  { number: 38, landmark: "Ice All Over", twist: "Whispering Wind" },
  { number: 40, landmark: "Blasted Waste", twist: "Monkeys with Guns" },
  { number: 43, landmark: "Long and Thin", twist: "Shipwrecked Explorers" },
  { number: 46, landmark: "Creeping Moss", twist: "Metal Skeletons" },
  { number: 50, landmark: "Steel Spires", twist: "Sand Wraiths" },
  { number: 54, landmark: "Blooded Bushes", twist: "Huge Spiders" },
  { number: 57, landmark: "Spiral Mountain", twist: "Harmless, Cute Piggies" },
  { number: 60, landmark: "Hot and Dry", twist: "Advanced Fish-People" },
  { number: 62, landmark: "Misty", twist: "Terrible Lizard Eggs" },
  { number: 64, landmark: "Grand Canyon", twist: "Silver Statues" },
  { number: 67, landmark: "Delicious Fruit", twist: "Meteor Armour" },
  { number: 70, landmark: "Ruined Temple", twist: "Doomsday Device" },
  { number: 75, landmark: "High Walls", twist: "Time Machine" },
  { number: 77, landmark: "Glass Towers", twist: "Crashed Sky-Boat" },
  { number: 80, landmark: "Lone Mountain", twist: "New Energy Source" },
  { number: 82, landmark: "Blue Grass", twist: "Font of Immortality" },
  { number: 84, landmark: "Yellow Rock", twist: "Ghost Army" },
  { number: 86, landmark: "Piles of Skulls", twist: "Ruby-Growing Tree" },
  { number: 89, landmark: "Oversized Fungus", twist: "Astral Vessel" },
  { number: 90, landmark: "Dense Cacti", twist: "Island is Giant Turtle" },
  { number: 92, landmark: "Choking Fog", twist: "It's Always Growing" },
  { number: 94, landmark: "Gusts of Wind", twist: "It's all a Hologram" },
  { number: 96, landmark: "Tiny Trees", twist: "No Time Passes Here" },
  { number: 98, landmark: "Elephant Herds", twist: "Steel Dinosaurs" },
  { number: 100, landmark: "Underwater", twist: "Slime Volcano" },
];

const IEatTheStuff = [
  { number: 1, description: "Delici...argh! STR Save or your guts explode." },
  { number: 2, description: "Delicious! Fruity. Quite satisfying." },
  { number: 6, description: "Tastes meaty. You regain any lost STR." },
  { number: 9, description: "Your insides feel cold, and liquid metal coats your bones. You always have Armour 1." },
  { number: 10, description: "Tastes pickled. You get real drunk." },
  { number: 13, description: "Woah. Hallucinations for d6 hours." },
  { number: 16, description: "Blech! Vomit now and for d6 hours." },
  { number: 18, description: "Tastes inky. You can read books instantly by waving your hand over them." },
  { number: 20, description: "Urgh... so salty. It's gross." },
  { number: 23, description: "Literally liquid gold. Lose d6 STR." },
  { number: 27, description: "Hot! Breathe Fire (d10) at whoever is right in front of you." },
  { number: 30, description: "Roll a Mutation." },
  { number: 34, description: "Turn Invisible for d6 minutes." },
  { number: 38, description: "Horrible pain for d6 minutes." },
  { number: 40, description: "Bready. You need never eat or drink again." },
  { number: 43, description: "Like liquid fish. Quite stirring." },
  { number: 47, description: "Blind for d6 hours!" },
  { number: 50, description: "Awful poison. Lose 2d6 STR." },
  { number: 54, description: "Lose 2d6 DEX. Turn to stone at DEX 0." },
  { number: 57, description: "Lose 2d6 WIL. Turn into an insane monster at WIL 0." },
  { number: 60, description: "It's okay I guess, for slime." },
  { number: 62, description: "Gain an evil voice in your head forever." },
  { number: 64, description: "Gain a helpful voice in your head forever." },
  { number: 67, description: "It's the best! You crave more." },
  { number: 70, description: "Lose 1 WIL each day until you eat some more." },
  { number: 71, description: "Invigorating! Gain 1d6 STR for d6 hours." },
  { number: 74, description: "Mind-Opening. Gain 1d6 WIL for d6 hours." },
  { number: 76, description: "Zippy! Move at double pace for d6 hours." },
  { number: 78, description: "First taste is gross. Second is delicious." },
  { number: 81, description: "Your mouth seals shut for d6 hours." },
  { number: 87, description: "Go on a rampage for d6 turns." },
  { number: 90, description: "Your voice now echoes." },
  { number: 92, description: "Your voice is permanently higher pitched." },
  { number: 96, description: "Rapid hair growth, permanently." },
  { number: 100, description: "Like Honey! Heals any ailment." },
];

const isThisAnArcanum = [
  { number: 1, form: "Throne", isItArcanum: "Nope!", power: "Cosmic Travel" },
  { number: 2, form: "Chest", isItArcanum: "No, but valuable!", power: "Time Distortion" },
  { number: 6, form: "Rod", isItArcanum: "Just weird.", power: "Cosmic Summoning" },
  { number: 9, form: "Wand", isItArcanum: "Just bait for a trap.", power: "Astral-Transcendence" },
  { number: 10, form: "Ring", isItArcanum: "No but still deadly.", power: "Telekinesis" },
  { number: 13, form: "Cube", isItArcanum: "The thing itself is a trap!", power: "Elemental Blast" },
  { number: 16, form: "Bell", isItArcanum: "Actually really boring.", power: "Slow Painful Death" },
  { number: 18, form: "Lantern", isItArcanum: "No, but some value.", power: "Disintegration" },
  { number: 20, form: "Brooch", isItArcanum: "Yes! Wait... no.", power: "Flight" },
  { number: 23, form: "Gem", isItArcanum: "Quite techy, but no.", power: "Size Distortion" },
  { number: 27, form: "Telescope", isItArcanum: "Obviously not.", power: "Plant Control" },
  { number: 30, form: "Lens", isItArcanum: "Find an expert and roll again!", power: "Mass-Creation" },
  { number: 34, form: "Dagger", isItArcanum: "No.", power: "Energy-Creation" },
  { number: 38, form: "Pistol", isItArcanum: "Otherworldly, but no.", power: "Thing go BOOM!" },
  { number: 40, form: "Musket", isItArcanum: "A fake.", power: "Unlock Primal Rage" },
  { number: 43, form: "Sphere", isItArcanum: "Just arty.", power: "Persuasion" },
  { number: 46, form: "Hammer", isItArcanum: "Just incredibly old.", power: "Auditory Illusions" },
  { number: 50, form: "Headband", isItArcanum: "Yes! But it's trapped.", power: "Visual Illusions" },
  { number: 54, form: "Bracers", isItArcanum: "Absolutely.", power: "Liquify Matter" },
  { number: 57, form: "Flute", isItArcanum: "Sure, but it's really ugly.", power: "Blast Minds" },
  { number: 60, form: "Drum", isItArcanum: "Yeah, but it smells so bad.", power: "Read Thoughts" },
  { number: 62, form: "Huge Machine", isItArcanum: "Sure is!", power: "Create Deadly Traps" },
  { number: 64, form: "Mirror", isItArcanum: "Yes, and valuable anyway!", power: "Summon the Dead" },
  { number: 67, form: "Painting", isItArcanum: "Unsettling, but yes.", power: "Hypnotic Music" },
  { number: 70, form: "Staff", isItArcanum: "Yes, but caked in dust.", power: "Dull Senses" },
  { number: 75, form: "Helmet", isItArcanum: "Sure, but not working now.", power: "Venom Ray" },
  { number: 76, form: "Breastplate", isItArcanum: "It might be... it is!", power: "Great Knowledge" },
  { number: 77, form: "Rock", isItArcanum: "Yes, and you've heard of it.", power: "Communicate Great Distances" },
  { number: 80, form: "Boulder", isItArcanum: "Yes! Just like in the story!", power: "Arm the Masses" },
  { number: 82, form: "Horn", isItArcanum: "Yes, and safe to use too.", power: "Destroy Structures" },
  { number: 84, form: "Tusk", isItArcanum: "Very much so.", power: "Unnatural Slumber" },
  { number: 86, form: "Sword", isItArcanum: "Yep!", power: "Spread Insanity" },
  { number: 89, form: "Tablet", isItArcanum: "Obviously.", power: "Possession" },
  { number: 90, form: "Engine", isItArcanum: "Sure, but looks so dangerous.", power: "Create Servants" },
  { number: 92, form: "Anvil", isItArcanum: "Yes!", power: "Release Unstoppable Creature" },
  { number: 94, form: "Dice", isItArcanum: "Yes, but needs attention.", power: "Release Benevolent Spirit" },
  { number: 96, form: "Chains", isItArcanum: "Yes, but not obviously.", power: "Swap Materials" },
  { number: 98, form: "Cannon", isItArcanum: "No... wait! No.. WAIT! YES!", power: "Sensory Overload" },
];

const mutations = [
  { number: 1, mutation: "Giant Head" },
  { number: 2, mutation: "Bone Claws (d6 Damage)" },
  { number: 6, mutation: "Bat Wings" },
  { number: 8, mutation: "Spit Acid (d8 Damage)" },
  { number: 10, mutation: "Third Eye (sense clues about people)" },
  { number: 12, mutation: "Covered in Barnacles" },
  { number: 14, mutation: "Nature Kinship (talk to animals and plants)" },
  { number: 16, mutation: "Illusionist (fool one person at a time)" },
  { number: 18, mutation: "Chitinous Shell (Armour 1)" },
  { number: 20, mutation: "Venom (d6 STR Loss on Critical Damage)" },
  { number: 23, mutation: "Spider Climb" },
  { number: 25, mutation: "Boneless" },
  { number: 27, mutation: "Bloodsucker (regain lost STR when you feed)" },
  { number: 30, mutation: "Compound Eyes (see all around you)" },
  { number: 34, mutation: "Bug Wings" },
  { number: 38, mutation: "Gills" },
  { number: 40, mutation: "Toady Skin" },
  { number: 42, mutation: "Glorious Mane" },
  { number: 44, mutation: "Slug-Like" },
  { number: 47, mutation: "Cyclops" },
  { number: 50, mutation: "Constant Drooler" },
  { number: 54, mutation: "Red-Gaze (d8 Damage)" },
  { number: 57, mutation: "Ruster (touch rusts metal)" },
  { number: 60, mutation: "Huge Jaws" },
  { number: 63, mutation: "Cocoon (sleep in an Armour 2 shell)" },
  { number: 66, mutation: "Prehensile Tail" },
  { number: 70, mutation: "Echolocation" },
  { number: 74, mutation: "Heat Vision (see heat signatures)" },
  { number: 78, mutation: "Devourer (eat anything for nourishment)" },
  { number: 80, mutation: "Living Hive (swarm of bugs live in you)" },
  { number: 82, mutation: "Explosive (d12 Damage blast when you die)" },
  { number: 84, mutation: "Spray Ink" },
  { number: 86, mutation: "Morph (change face at will)" },
  { number: 88, mutation: "Void (annihilate objects you grasp)" },
  { number: 90, mutation: "Spores (choke opponents)" },
  { number: 93, mutation: "Camouflage" },
  { number: 96, mutation: "Psychedelic Skin" },
  { number: 98, mutation: "Horns" },
  { number: 100, mutation: "Hooves" },
];
